### ISSUE TITLE
Remove duplicated functionality from hera_cal.redcal

### ISSUE THREAD

**Issue by AaronParsons** [HERA-Team/hera_cal#100]
More than 50% of the code in redcal doesn't actually relate to redcal (noise, apply_gains, data simulation).  Some of this functionality is being brought over to hera_sim.  We should migrate the rest (or move into a different hera_cal module) and whittle the hera_cal.redcal code down to just code relating to redundant calibration.

**Comment by jsdillon** [comment]
I'm changing the name of this issue to reflect our current thinking.

Regarding noise and sim_red_data, we can move these out but it requires making hera_sim a prerequisite for hera_cal. We can do that, but I'd like to see hera_sim on travis and coveralls and better documented. This seems pretty low priority. Also, as far as I can tell, hera_sim isn't even passing it's own unit tests. 

That said, the apply_gains functionality currently duplicates functionality in apply_cal. I'm going to make a new issue (#320) and close this one until hera_sim is on firmer footing.
