### ISSUE TITLE
should ants flagged by firstcal metrics not be used in omnical?

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_cal#103]

**Comment by dannyjacobs** [comment]
wait what?  If we don't get a firstcal, can't get a omni.

**Comment by adampbeardsley** [comment]
I'm talking about antennas which produced firstcal delays, but firstcal_metrics deemed to be untrustworthy. We don't want these contaminating omnical solutions for other antennas.

**Comment by dannyjacobs** [comment]
Things should be flagged in RTP only when not doing so would break later steps.  The stuff @AaronParsons was showing today on the software telecon suggested that when delays went occasionally wonky, omnical was able to ride it out (still found ok solutions for other antennas).

**Comment by plaplant** [comment]
I agree with @dannyjacobs, we should throw away as little data as possible. If we see that bad firstcal antennas give bad omnical solutions, then we could reconsider. But I think it's okay as is

**Comment by adampbeardsley** [comment]
ok
