### ISSUE TITLE
Tolerance bug in aa_to_info 

### ISSUE THREAD

**Issue by zakiali** [HERA-Team/hera_cal#105]
There is a bug in aa_to_info where the tolerance is too low for the redundant groups to be calculated correctly. This was not a problem before because we were using idealized positions. Now that we are using real antenna positions (get_aa_from_uv), this needs to fixed.

Quick fix is to raise tolerance to 1. This needs to be double checked that all the groups are being calculated correctly.

**Comment by plaplant** [comment]
This was done in PR #110.
