### ISSUE TITLE
Come up with new rotated antennas metric

### ISSUE THREAD

**Issue by zakiali** [HERA-Team/hera_cal#132]
Currently firstcal iteratively detects 180 degree rotated antennas and attempts to fix this rotation by multiplying data by -1 before running firstcal again. However, there are issues where antennas are erratically being labelled as rotated on each iteration causing either firstcal to not converge or to converge but with wrongly accused rotated antennas. These rotations cause small discontinuities in the delay solutions for the rotated antennas. 

The rotated antennas with HERA-47 seem to be stemming from the interplay between antennas with PAM's and NRAO receivers. Only antennas with NRAO receivers are being flagged as rotated antennas.

**Comment by jsdillon** [comment]
Made irrelevant by #370
