### ISSUE TITLE
verify accuracy of hera_cal.abscal.delay_lincal offset solver

### ISSUE THREAD

**Issue by nkern** [HERA-Team/hera_cal#133]
`delay_lincal` in `abscal` solves for per-antenna delays and offsets, which could be a viable replacement for `firstcal`. the delay solver seems to work fine, but more work needs to be done to verify the accuracy of the offset solutions in order for this to replace firstcal

**Comment by jsdillon** [comment]
This is related to #250 so I'm going to make it an H2CB RTP issue.

**Comment by jsdillon** [comment]
Like #250, this was also made irrelevant by #370
