### ISSUE TITLE
Test omni_apply on cross-pol data

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_cal#14]

**Comment by bhazelton** [comment]
we need unit tests on this

**Comment by SaulAryehKohn** [comment]
It's "tested" with a combination of PRs #19 and #21 . But we need unit tests now....

**Comment by SaulAryehKohn** [comment]
We're working on this in PR #26

**Comment by SaulAryehKohn** [comment]
Addressed in PR #41
