### ISSUE TITLE
fft_dly of abscal needs refinement at 0.5 ns level

### ISSUE THREAD

**Issue by nkern** [HERA-Team/hera_cal#141]
in noise-free simulation, `fft_dly` results deviate from truth at the 0.5 ns level. the algorithm can be refined to resolve this
![fft_dly](https://user-images.githubusercontent.com/4307358/35189035-67a05cda-fdf7-11e7-941e-2f0c2eb99b3f.png)

**Comment by jsdillon** [comment]
This is probably needed for #250, so I'm adding an H2CB RTP milestone.

**Comment by jsdillon** [comment]
While digging into some issues with fft_dly and phase offsets in firstcal for the purpose of validated Abscal and Redcal combined, I stumbled on this page: https://dspguru.com/dsp/howtos/how-to-interpolate-fft-peak/

The method we've been using, the quadratic method, for interpolating a peak, is one of many. I tried implementing the one that is supposed to work the best, "Quinn's Second Estimator", which is spelled out in this paper: https://ieeexplore.ieee.org/document/558515

The results were surprisingly good:

![screen shot 2019-03-06 at 11 27 08 pm](https://user-images.githubusercontent.com/5281139/53939303-82b1a480-4067-11e9-89f2-b38c0d11dbfa.png)

![screen shot 2019-03-06 at 11 27 12 pm](https://user-images.githubusercontent.com/5281139/53939307-85ac9500-4067-11e9-8153-7ba7ba790554.png)

I am implementing this in #444.

**Comment by nkern** [comment]
I assume you flipped the legend? Looks like it does worse..

**Comment by jsdillon** [comment]
Fixed.
