### ISSUE TITLE
How is Abscal and HERACal different in cal_formats.py

### ISSUE THREAD

**Issue by zakiali** [HERA-Team/hera_cal#145]
Right now abscal (the module) uses HERACal and not Abscal. Can we combine the objects for a single cal_formats class since cal_formats should be the same (theoretically), or deprecate Abscal?

**Comment by nkern** [comment]
I wasn't quite sure what `AbsCal` in `cal_formats.py` was doing differently than `HERACal`.  I assumed this was something Penn was using. I don't want to deprecate it if its something they are actively using it.

**Comment by nkern** [comment]
ah I see, `AbsCal` assumes a single bandpass and pads them out to all times, whereas `HERACal` takes full time and freq gains. Seems like this capability could just be something `HERACal` does automatically if detected..

**Comment by SaulAryehKohn** [comment]
`AbsCal` was hacked together by @plaplant , Ridhima and I this summer to apply gains from CASA to MIRIAD files. I don't think anyone is actively using it. @nkern I think your progress in the past couple of months has pretty-much deprecated it!

**Comment by jsdillon** [comment]
Shall we delete it then? If either of you want it, I think it probably belongs in hera_sandbox.

**Comment by plaplant** [comment]
I'm okay with deleting it. It served its purpose for @SaulAryehKohn's paper, but we can migrate it to the sandbox for posterity.

**Comment by jsdillon** [comment]
Ok, I've removed in it PR #150.

**Comment by plaplant** [comment]
PR #150 has been merged. Closing this issue
