### ISSUE TITLE
Add flags, quality, and history to abscal calfits

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_cal#148]
Quality should be omnica's chi^2 copied over.
Flags should be an np.and(input flags) (if all visibilities flag a chan/time, then it's also flagged in the calibration.

**Comment by jsdillon** [comment]
@nkern Bumping this. I think it's currently an issue for the pipeline.

**Comment by nkern** [comment]
this actually isn't an issue w/ `abscal`

**Comment by nkern** [comment]
I will have a `hera_cal` PR that takes the (1) route. I'm working w/ @plaplant to make sure the `do_ABSCAL.sh` script is updated to reflect the necessary changes.

**Comment by jsdillon** [comment]
Addressed in #226
