### ISSUE TITLE
Update calfiles produced by firstcal/omnical to be explicitly "redundancy" type

### ISSUE THREAD

**Issue by plaplant** [HERA-Team/hera_cal#153]
A recent PR in pyuvdata (https://github.com/HERA-Team/pyuvdata/pull/290) added sky-based calibration as a type to the calfits implementation. The old format is "redundancy" type, and is applicable to firstcal and omnical calibration solutions. We should update the functions for producing these calfiles to explicitly set its type, as well as mark abscal as a "sky-based" type (as well as add the corresponding metadata). It may also mean that tests break in the meantime, but remains to be seen.

**Comment by plaplant** [comment]
This was addressed in PR #155.

**Comment by jsdillon** [comment]
It looks like the unittests are producing warnings because of this issue. I'm reopening it.

**Comment by nkern** [comment]
the warnings are b/c the `calfits` files we have on disk are not written out w/ a cal_style. `pyuvdata` has a backwards compatibility mechanism that assigns it a default if its not written, so its an "expected" warning in that sense. to get rid of the warning, you just need to read it in and write it back out and commit it to the repo.

**Comment by plaplant** [comment]
As @nkern said, we can read, write, and commit the new files. Another possibility is to wrap the calls to read them with the pyuvdata test function that silences (expected) warnings without raising them.

I agree in principle that it's a little sloppy for there to be warnings in tests, but there are quite a few `divide by zero encountered in divide` and `invalid value encountered in divide` errors that were introduced in past PRs and have so far been unaddressed. I'm closing this issue here because the root issue I raised was addressed in PR #155, but you can open a new one about getting rid of errors in tests if you want.

**Comment by nkern** [comment]
I re-wrote them with an appropriate `cal_style` in #160, so this should be completely taken care of.
