### ISSUE TITLE
Ensure time matches between calibration solution and data file

### ISSUE THREAD

**Issue by plaplant** [HERA-Team/hera_cal#154]
In `omni_apply`, we do not check that the time values match between the calibration solutions and the data files. This will become especially important as we add support for sky-based calibration tied to specific LST and JD values. We should add code for checking time values match, and possibly allow for interpolation if they don't match.

**Comment by bhazelton** [comment]
In particular, Miriad files have their timestamps at the beginning of the integrations while pyuvdata objects have their timestamps at the center of the integrations. When pyuvdata cal objects are made, the times should be adjusted if needed to be correct.

**Comment by jsdillon** [comment]
We saw that data (via the flagging npzs) and the calfits times match up to 1e-9 days, which is better than half an integration (see #304), so we can close this issue.
