### ISSUE TITLE
Use `astropy` for RA calculation instead of `ephem`

### ISSUE THREAD

**Issue by plaplant** [HERA-Team/hera_cal#164]
Using `ephem` to perform calculations of RA yields incorrect results. We should use `astropy` to do it instead.

**Comment by jsdillon** [comment]
I asked about the same thing and @nkern said you said ephem was fine for what he was doing. Are we miscommunicating here?

**Comment by nkern** [comment]
naw, paul and I thought it was fine, but @bhazelton informed us after that `ephem` is apparently still slightly incorrect

**Comment by nkern** [comment]
still trying to see exactly how to do the calculation using only `astropy`. its currently not clear to me how this works...

**Comment by jaguirre** [comment]
where in the code is this?  I've spend a fair amount of time wrestling with astropy coordinates ...

**Comment by plaplant** [comment]
@jaguirre here is where the calculation is being done right now: https://github.com/HERA-Team/pyuvdata/pull/287/files#diff-7d62f05bd3d6a58723cde3facfa3af53R297. Any insight is appreciated!

**Comment by nkern** [comment]
the conversion from JD -> LST using `astropy` is understood i think. The code in `pyuvdata` and the code in `hera_cal` seem to be using the same functionalities with the `astropy.time.Time` class to do this. the question we are concerned with is to convert a Local Sidereal Time --> Equatorial right ascension (preferably in J2000 epoch) at zenith for a time integration. you can do this with `pyephem`, but we are concerned that `pyephem` is inaccurate.

**Comment by jsdillon** [comment]
This is done, right @nkern ?

**Comment by nkern** [comment]
ya
