### ISSUE TITLE
Integration tests with simulations

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/hera_cal#18]
FHD/PRISim simulation -> fake gains -> calibrate -> image

**Comment by wenyang-li** [comment]
[heracal-tests-mwa.pdf](https://github.com/HERA-Team/hera_cal/files/1125687/heracal-tests-mwa.pdf)
I just appended the simulation section to my previous memo for MWA test. Please let me know if you have any questions or if I have wrote anything wrong. Thank you.

**Comment by jsdillon** [comment]
Based on that memo, the consensus at the CHAMP meeting is that we can close this issue.
