### ISSUE TITLE
do we really want to enforce a strict bin width in the lstbinner?

### ISSUE THREAD

**Issue by nkern** [HERA-Team/hera_cal#187]
we currently restrict an LST bin width such that 2pi is equally divisible by it. this was done to limit human error, and for making fringe-rate filtering easier, however, we brought up the idea in an analysis telecon to make this more flexible for other users of the software.

**Comment by jsdillon** [comment]
No one has come forward clamoring for this feature, so I think we can close this issue. If it comes up, we can readdress it.
