### ISSUE TITLE
omni_apply doesn't work with UVCal.ant_array definition

### ISSUE THREAD

**Issue by nkern** [HERA-Team/hera_cal#199]
it seems that `hera_cal.omni.omni_apply` was written assuming the `UVCal.ant_array` object was the same as the `UVCal.antenna_numbers` object, which isn't the case. Our new `io.write_cal` does not assume this, and as such calfits files written with `io.write_cal` are not properly applied using `omni_apply`. We need a new `apply_cal` function that handles this appropriately.

**Comment by jsdillon** [comment]
I think what I'm building to address #197 will also address this.

**Comment by jsdillon** [comment]
I started on this here: https://github.com/HERA-Team/hera_cal/blob/update_cal/hera_cal/update_cal.py

I haven't written any tests yet. Also, we need a run script with command line argument parsing. Was going to work on it next now that calibration smoothing is in review.

**Comment by nkern** [comment]
ah okay, i have an `apply_cal` function (using full Jones matrix formalism to possibly incorporate D-terms) with a PR that will be ready in a few minutes...

**Comment by nkern** [comment]
* with a run script too...

**Comment by jsdillon** [comment]
Ah, ok. Does it do the same thing? i.e. does it address #197? Because if so, I can not bother finishing what I've got here.

**Comment by nkern** [comment]
just for clarity, the issue turns out not to be w/ `omni_apply`, but with the fact that the `pyuvdata` documentation for `UVCal.ant_array` was not in-line with how `UVCal.ant_array` was being used by both `hera_cal.omni` and `pyuvdata.UVCal` itself. The docs have been changed in `pyuvdata` to be consistent with how `ant_array` is being used. In light of that, `omni_apply` should work fine..
