### ISSUE TITLE
Replace flagged data in .uvOCRS files with delay-filtered models (but keep them flagged)

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_cal#282]

**Comment by nkern** [comment]
If i'm not mistaken, this is exactly what the PR I made to `hera_cal` recently attempts to do. So we already have the capabilities to do this..

**Comment by nkern** [comment]
@bhazelton ah yes, we do need to add a comment in the history. thanks for the catch

**Comment by jsdillon** [comment]
I think you're right nick. We just need run io.update_vis twice... basically both writing the .uvOCRSD and also updating the input .uvORCS

**Comment by jsdillon** [comment]
Given that we're trying to minimize the number of times we write down things that are the same size as the data, I think we can close this issue. It wasn't part of IDR2.1 and so I don't think we're ever going to explicitly write this data product down going forward (since future IDRs will make fewer/no copies of the data before LST-binning... except maybe the CLEAN model itself).

However, @nkern is right that such a data product is constructable with what is currently produced relatively straightforwardly.
