### ISSUE TITLE
Fix unit mismatch in redundant_bl_cal

### ISSUE THREAD

**Issue by AaronParsons** [HERA-Team/hera_cal#287]
https://github.com/HERA-Team/hera_cal/blob/6085944949e0ab21a85093989754454b8b6d055b/hera_cal/firstcal.py#L105

redundant_bl_cal takes in freqs, which it assumes is in GHz, but returns delays in seconds.  Change to make freqs be in Hz, and return delays in seconds without the 1e9 division.  This is a backward incompatible change and will have to be propagated into any code that uses this function.

**Comment by jsdillon** [comment]
Made irrelevant by #384.
