### ISSUE TITLE
Abscal: Add flagging for when the sun is within X degrees of the horizon 

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_cal#289]
Perhaps we also want to flag when the sun is a few degrees below the horizon too, so let's expose that parameter to makeflow.

If only part of the file is flagged in this way, we might want to run all of abscal and then impose the flags after the fact... that way we can use averages to get the delay slope right.

**Comment by nkern** [comment]
addressed by #290 . i don't think we want to flag after the fact and let data pass through abscal that we know could be contaminated by the sun, *especially* if we are doing any averaging across time
