### ISSUE TITLE
perform time-broadcast of flags on all flag files

### ISSUE THREAD

**Issue by nkern** [HERA-Team/hera_cal#296]
Write a script to load in flag `.npz` files and perform a per-visibility broadcast across all times per-frequency if fraction flagged exceeds some tolerance

**Comment by jsdillon** [comment]
I think this belongs in hera_qm

**Comment by jsdillon** [comment]
I think this is getting subsumed in a larger re-architecture of xrfi (see #299), so I'm closing this.
