### ISSUE TITLE
Perform RFI excision by comparing best-guess CLEAN components to smoothly-calibrated data with no masking

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_cal#299]
A new idea for xrfi that @AaronParsons proposes that we want to look into post IDR2.1:

Do our best guess to create smooth gains which interpolate over rfi flags. Then apply this to data and delay filter (with our best-guess flags so far) to get CLEAN components.

Then we want to compare those CLEAN components to smoothed-abscal applied data to create the definitive RFI mask.

**Comment by jsdillon** [comment]
A bit more detail on this proposal from today's discussion at Berkeley (with me, @zakiali, @nkern, and @AaronParsons):

1. Produce abscal gains and normalized omnical chi^2 (see #301)
2. Flag calibration solutions based on the above
3. Smooth calibration solutions
4. Apply smoothed calibration solutions to raw data for all channels and frequencies, even those that are flagged.
5. Flag data using above flags and perhaps also flags based on running xrfi on calibrated data.
6. Perform delay filter on flagged and smooth-abs calibrated data
7. Subtract CLEAN model from smooth-abs calibrated data and perform xrfi on that residual. These are the *only* flags that actually get applied to data (perhaps also incorporate normalized chi^2-based flags) 

Additionally, we want to rethink thresholding and broadcasting. The idea is to compute the sigma(t,f,b) using the medfilt function currently in xrfi. Assuming that RFI happens to all baselines, we reduce this to sigma(t,f) by averaging in quadrature. That can happen on a file-by-file basis. Next, we look at a whole day of sigma(t,f) and perform the watershed algorithm to turn this into flags(t,f) parameterized by sig_init and sig_adj. Finally, we want to perform thresholded broadcasting across channels (for each integration) and simultaneously a thresholded broadcasting across times (for each channel) using a 1D convolution kernel with a physically-motivated timescale instead of a whole day.

**Comment by adampbeardsley** [comment]
There are quite a few pieces to work on here. I'm going to make some smaller issues in hera_qm that reference this master issue. Specifically I'm trying to divide things into top level run modes and the modular infrastructure to enable them.

**Comment by jsdillon** [comment]
@adampbeardsley I think we can close this as something we're not planning to implement... right?

**Comment by adampbeardsley** [comment]
That's right. We saw some issues using the clean method and resorted to using the normal median/mean filters for detrending. It's possible we may want to revisit cleaning in the future, but I'm happy to close this for now.
