### ISSUE TITLE
[IDR2.1] propagating noise through calibration pipe

### ISSUE THREAD

**Issue by nkern** [HERA-Team/hera_cal#317]
Following the 6/7 pspec meeting, and based on the weird spectral structure in the variance plots from the IDR2.1 LSTbinner, we decided we need to get a handle on how the calibration pipeline affects noise in our raw data. To this end, we decided to start by getting a post-correlator noise model, generating some fake data that follow that model, and propagating that through the analysis pipeline through to the LSTbinner.

@jsdillon volunteered to start working on the noise model, with me and @plaplant working on running it through the analysis pipe.

**Comment by jsdillon** [comment]
I think that this has largely been addressed by the consistency between the noise observed in the variance of days LST-binned together, the noise observed by freq/time differencing, and the noise predicted from autocorrelations, as demonstrated in this (draft) IDR 2.2. memo: https://nbviewer.jupyter.org/github/HERA-Team/hera_sandbox/blob/master/jsd/IDR2_2/IDR2.2_Memo.ipynb
