### ISSUE TITLE
new abscal model for idr3.1

### ISSUE THREAD

**Issue by nkern** [HERA-Team/hera_cal#324]
same methodology as idr2.1, but stringing together multiple fields for largeer LST coverage

**Comment by nkern** [comment]
Done. Located in `/lustre/aoc/projects/hera/nkern/idr3_abscal_models/full_model` under `zen.*.xx.HH.uvRXL.uvh5` for the stitched models and `zen.*.xx.HH.uvRXLS.uvh5` for their delay CLEAN model counterparts. Only `xx` and `yy` visibility polarizations exist.

**Comment by nkern** [comment]
A notebook describing the calibration for each field and inspection of the visibilities (pre and post stitching) can be found in `/lustre/aoc/projects/hera/nkern/idr3_abscal_models/idr3_model_info.ipynb`

**Comment by jsdillon** [comment]
One request, @nkern: can you merge them into a single file that contains both polarizations? We're moving toward all files being 4-pol (or 2-pol when appropriate).

**Comment by jsdillon** [comment]
Looks like we're done, @nkern. Want to close this?
