### ISSUE TITLE
Figure out whether 6-minute gain oscillations are present in IDR2.1

### ISSUE THREAD

**Issue by AaronParsons** [HERA-Team/hera_cal#325]
Anecdotally, we have evidence both for and against the presence of 6 min gain oscillations in HERA data.  On the one hand, differencing visibilities (led by Miguel) seems to indicate a residual with a 6-minute periodicity.  On the other hand, the gain solutions out of abscal don't seem to have that same periodicity.  We need to gather the various lines of evidence and reach a conclusion.

**Comment by jsdillon** [comment]
@nkern can you post some of the plots you produced on this?

**Comment by nkern** [comment]
See `hera_cal.tempcal` for the tools used to make these data products.

![auto_oscillations](https://user-images.githubusercontent.com/4307358/63455863-7a290c80-c402-11e9-82ea-2140fd5375c4.png)
^ Time-smoothed auto-correlation (~15-minute scale) divided by auto-correlation

This shows a clear sinusoidal pattern that is coherent across antennas, and seems to have the same amplitude across the bandwidth. If we average across frequency we get the following.

![auto_gains](https://user-images.githubusercontent.com/4307358/63455995-d855ef80-c402-11e9-8b4b-7cb947a951c6.png)
^ Frequency-averaged gain oscillation for a few antennas, and the frequency & antenna average shown in black. 

The take away here is that: 6-minute gain oscillations are seen at the 0.1 % level in the auto-correlations and that we can probably do a good job calibrating this out with highly restricted degrees of freedom, being a single number per time for all antennas and all frequencies. See the HERA-Comissioning issue on this to see the time profile of the container temperature, which shows the same shark-fin like time profile

**Comment by jsdillon** [comment]
Interestingly, we do not see the six minute oscillation in the temporal power spectrum of the redcal + abscal calibration solutions from IDR2.2, however given its tiny amplitude we expect to see it marginally if at all: http://reionization.org/wp-content/uploads/2013/03/HERA072_Calibration_Temporal_Structure_Memo.pdf

Regardless, I think we can safely close this issue and say that we do not believe this to be a leading order effect in H1C analysis that needs to be taken into account.
