### ISSUE TITLE
Abscal appears to be completely flagging antenna 26 every day in IDR2.1

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_cal#327]
Looking at temporal and spectral structure in the IDR2.1 gains, Naomi found that for some reason antenna 26 is getting flagged for all times and frequencies, starting with the `.abs.calfits` files (it's not in bad_ants or flagged in omnical).

We need to figure out why abscal is flagging this antenna and whether or not that's the right thing. 

My hunch is that the antenna is flagged in the abscal model visibilities and that flag is getting propagated, even though we're only solving for the omnical degeneracies and in theory it shouldn't be flagged by abscal.

Thoughts, @nkern?

**Comment by jsdillon** [comment]
@nkern did we close this in #411?

**Comment by nkern** [comment]
No, I did some tests and couldn't find what you were talking about--abscal doesn't flag antennas that aren't in the model when solving for the TipTilt slope and average amplitude..

**Comment by jsdillon** [comment]
I see. And does it flag antennas that are flagged in the model (rather than just not in it)?

**Comment by jsdillon** [comment]
Not 100% sure what we did, but between the abscal model updates and the new abscal run script, this appears to be fixed for IDR2.2.

![Screen Shot 2019-04-30 at 12 41 29 PM](https://user-images.githubusercontent.com/5281139/56988633-63099a80-6b45-11e9-89fe-6d0ec6699f2d.png)
