### ISSUE TITLE
re-LST bin with fixed_lst_start

### ISSUE THREAD

**Issue by nkern** [HERA-Team/hera_cal#329]
The current output of the LST binner starts the LST grid at the first LST in the data. This means that for multi-group splits (e.g. grp1 and grp2 in two_group) have different starting points for their LST grids, and thus have different filenames. We thought originally this wasn't that big of a deal, as one can always load in the data and trim off excess LSTs, but from a pipelining perspective it is rather cumbersome to deal with. I am going to re-LSTbin the data with a fixed LST start, and if we decide to use these outputs, we will need to update the filenames in the idr2.1 memo.

**Comment by jsdillon** [comment]
I've updated the memo on hera_sandbox and asked danny to update the html too.
