### ISSUE TITLE
Get abscal ready for IDR3 / H2C RTP

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_cal#335]
This includes:

* Making it python 2 and python 3 compatible (#318)
* Implementing partial data loading (#319) using the HERAData class in #331 and deprecating old cal_formats (see #330) in favor of hera_cal.io
* Fix the issue where dead ants in the model flag the data (#327)
* Robustify tests (#262)
* Update the example notebook (#266)

**Comment by jsdillon** [comment]
One other thing: we should allow abscal to take in raw data and an omnical calibration solution (assuming that we're not going to be rewriting data on disk that we don't need to).

**Comment by nkern** [comment]
#411 makes `abscal` compatible with `uvh5` files and allows for passing calibration solutions and raw data for on-the-fly apply cal.
