### ISSUE TITLE
Get the LST-binner ready for IDR3

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_cal#340]
This includes:

* Making firstcal python 2 and python 3 compatible (#318)
* Implementing partial data loading (#319) using the HERAData class in #331
* Using pyuvdata standard calibration strings (see #169 and #331 as an example)
* (if time permits), implementing new metrics for finding bad days (#258)

**Comment by nkern** [comment]
#411 makes `lstbin` compatible with `uvh5` file format. A future PR will make it explicitly partial IO capable.

**Comment by jsdillon** [comment]
#482 added partial I/O support. While #258 hasn't been addressed, I think this issue can be closed.
