### ISSUE TITLE
IDR2.1 antenna 84 one dipole dead

### ISSUE THREAD

**Issue by keelder** [HERA-Team/hera_cal#343]
I have been working the cross-pol (i.e. xy and yx) IDR2.1 data and taking the delay transform to look at the amplitude of antenna pairs. It appears that one of the dipoles on antenna 84 is dead. This is a waterfall plot of the entire IDR2.1 run with antennas 11 (which I know is working fine) and 84:
![idr2 1_full_run_11_84](https://user-images.githubusercontent.com/40301301/42782771-b52817c6-88fe-11e8-9fa8-aa5c0df6a3ce.png)
 Has anyone else noticed a problem with 84? And could this be an issue with the calibration?

**Comment by nkern** [comment]
Hi Katherine, which directory is this from? Also, if you wanted to confirm that some part of the hardware from a dipole is malfunctioning, it might be useful to look at the antenna autocorrelations, as well as auto-dipole correlation (i.e. non cross-pol). Let me know what you find! thanks

**Comment by keelder** [comment]
Hi Nick, I'm working with the data from LSTBIN group 1 of 1. As for checking autocorrelations, I ran my waterfall script for antenna 84 with antenna 84. The cross polarized data came back with empty plots. Below are the plots I got for the xx and yy polarizations: 
![xx_yy_84_autocorr](https://user-images.githubusercontent.com/40301301/42844792-f1db7a30-89c8-11e8-82e7-709ed2f07d6a.png)

**Comment by jsdillon** [comment]
Could this be the same issue as #327?

**Comment by keelder** [comment]
I was able to pull files from earlier stages, so I am looking at the pre-LST binned 2458106 files. I reran my waterfall plots, again looking at the autocorrelation for antenna 84. 

Here is the result from the .uv files: 
![2458106_xx_yy_uv](https://user-images.githubusercontent.com/40301301/43173929-4f066082-8f6c-11e8-9fd5-f9ed1790b07a.png)

And here is the result from the .uvOCR files: 
![2458106_xx_yy_uvocr](https://user-images.githubusercontent.com/40301301/43173939-64bd16e6-8f6c-11e8-95d1-26d854268d84.png)

There is clearly still data in the files, so 84 has not been flagged yet. I am going to keep looking at more of the raw files and follow the pipeline to see if I can identify where the antenna started to be flagged.

**Comment by keelder** [comment]
@nkern can you check if the antenna is flagged in the abscal model?

**Comment by keelder** [comment]
I ran the .uvOCRS files and got this waterfall plot for antenna 84: 
![2458106_xx_yy_uvocrs_masked_84](https://user-images.githubusercontent.com/40301301/43226197-fd50e7b8-900f-11e8-8440-d96011967029.png)
The Y dipole is still not flagged at this point. I also checked on antenna 26 and it is not flagged either. 

As far as I can tell, the next step after this is LST-binning the data. Since the antennas have not been flagged up to this point, something must be happening during the LST-bin process that is flagging these antennas. 
@nkern can you look into the LST-bin pipeline and see where it could be flagging them? If it is consciously flagging antenna, that should be documented somewhere.

**Comment by nkern** [comment]
@keelder That's very interesting indeed. The LSTbinner should not introduce any new flags into the data.

I've looked at a few pre-LST binned files from `2458098` and  `2458116` and the 84-y dipole **is** flagged in those files.

**Comment by keelder** [comment]
@nkern which files were you looking at exactly? I was just looking at the .uv and .uvOR files for `2458098.14043` and 84-y dipole wasn't flagged. I also looked at the .json file and it didn't list 84 as being flagged.

**Comment by jsdillon** [comment]
Do we still care about this?

**Comment by jsdillon** [comment]
This doesn't appear to be true in IDR2.2, so I'm closing this issue.

![image](https://user-images.githubusercontent.com/5281139/61987551-6b4e6600-afcc-11e9-880e-322bbdd2721f.png)
(This is group 1 of 1 LST-binned data.)
