### ISSUE TITLE
Add license information to the repo

### ISSUE THREAD

**Issue by plaplant** [HERA-Team/hera_cal#345]
We should add a LICENSE file to the top level of the repo, as well as copyright information at the top of all source code. @jsdillon do you have a preference for which open source license we go with?

**Comment by jsdillon** [comment]
Done in https://github.com/HERA-Team/hera_cal/commit/7cf78aa9a8eef135f5d265fc4513e20531206b3e

**Comment by plaplant** [comment]
This doesn't address all aspects of the licensing. We also need to add copyright information to the top of the source code files.

**Comment by jsdillon** [comment]
Oh, I see. I'll take care of it.
