### ISSUE TITLE
Update code for QM's XRFI revamp

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_cal#354]
A lot of interfaces are changing with QM's XRFI revamp, so I'm preemptively filing an issue here to address it. For testing purposes, we can use QM's `xrfi_revamp` branch before it gets merged into master.
Things to update:
`scripts/omni_xrfi.py`
`scripts/apply_cal.py` (currently uses a flag npz, which will be a UVFlag h5 file in the future)
`scripts/smooth_cal_run.py` (flag npz)
`hera_cal/apply_cal.py`
`hera_cal/io.py` (load_npz_flags should be replaced, or add a load_uvflag function)

There is an issue in QM that the last item should be moved to QM, but given that load_vis and load_cal are in `hera_cal.io`, I'm not so convinced.

**Comment by adampbeardsley** [comment]
I just realized right after merging the xrfi revamp branch that this issue is suddenly much more urgent. We will probably need to build against hera_qm@f3e32c3cef36cbdf784d4028c5a1ef14c082a274 until we do this stuff.

**Comment by jsdillon** [comment]
Resolved by #398
