### ISSUE TITLE
repoint process_ex_ants

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_cal#365]
As requested, hera_qm has absorbed process_ex_ants. There is a slight change to the interface:
As is in `hera_cal.omni`:
`process_ex_ants(ex_ants, metrics_json='')`
Now in `hera_qm.metrics_io`:
`process_ex_ants(ex_ants=None, metrics_file=None)`
So the difference is that now both arguments are optional keywords, and they default to `None`. Note that passing `''` for ex_ants will still work (returning `[]`), but passing an empty string for the file will make it error.

**Comment by jsdillon** [comment]
Made irrelevant by #384.
