### ISSUE TITLE
Ant numbering bug in `aa_to_info`

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_cal#371]
https://github.com/HERA-Team/hera_cal/blob/e062f9192e8ae60b51f7ef103e981f1084ef26ab/hera_cal/omni.py#L330

If the only pol present is `['y']`, this line results in an index error because `int(i)` evaluates to `nant + ant`. I think this should be `antpos[i.ant(), 0], antpos[i.ant(), 1], antpos[i.ant(), 2] = x, y, z `, but I don't fully understand why we're using an `Antpol` object to begin with, so I'm not sure.

**Comment by jsdillon** [comment]
I was planning on deprecating all of this anyway. Is this a show stopper right now?

**Comment by adampbeardsley** [comment]
No, we can get around it for our use case. Interestingly a separate bug in QM was covering it up.

**Comment by jsdillon** [comment]
Made irrelevant by #384.
