### ISSUE TITLE
Move noise, sim_red_data, build_split_hex_array_with_outriggers, etc. into hera_sim

### ISSUE THREAD

**Issue by AaronParsons** [HERA-Team/hera_cal#379]
These functions really belong in a separate repo dedicated to modeling our array.  Discussion in https://github.com/HERA-Team/hera_cal/pull/370#discussion_r224169071 and https://github.com/HERA-Team/hera_cal/pull/370#discussion_r226383389.

**Comment by jsdillon** [comment]
Actually this is still open. I still need to rip these out of hera_cal. I'll do that shortly.
