### ISSUE TITLE
Remove top-level dependency on hera_qm

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_cal#387]
QM builds fail because QM is being imported at the top level in hera_cal:
https://travis-ci.org/HERA-Team/hera_qm/jobs/449507967
Can we move these imports into the function that uses it?

**Comment by adampbeardsley** [comment]
stop it.
https://travis-ci.org/HERA-Team/hera_qm/jobs/454255209
(line 13 of redcal)

**Comment by jsdillon** [comment]
Resolved in #395
