### ISSUE TITLE
Write hera_cal git hash to file outputs 

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_cal#394]

**Comment by jsdillon** [comment]
This should probably wait for #391

**Comment by plaplant** [comment]
@jsdillon is this still an issue?

**Comment by jsdillon** [comment]
Yes, I believe so.

**Comment by jsdillon** [comment]
This was discussed on 1/2/19 and it was decided to add this to all written file histories at the module level. I volunteered to do it.
