### ISSUE TITLE
Move capo.redcal into hera_cal

### ISSUE THREAD

**Issue by AaronParsons** [HERA-Team/hera_cal#40]

**Comment by jsdillon** [comment]
Have we done a side-by-side speed comparison yet?

**Comment by AaronParsons** [comment]
We haven't, but we need to be able to move forward with development and for that to happen, we need to be out of capo.

**Comment by jsdillon** [comment]
Ok. I think the next step is getting linsolve into HERA-Team. Certainly we
don't hera_cal.redcal using capo.linsolve. Do you want to do that or shall
I?

**Comment by jsdillon** [comment]
I've started a branch called [add-redcal](https://github.com/HERA-Team/hera_cal/tree/add-redcal).

It's got all capo dependencies removed except linsolve.

**Comment by jsdillon** [comment]
Done in #43
