### ISSUE TITLE
Fix documentation about window functions on 2D smooth_cal

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_cal#400]
https://github.com/HERA-Team/hera_cal/blob/ad75e567674d1bf1135fdae14f5ebf4ac16fc107/hera_cal/smooth_cal.py#L137

Make it clear the the window is only applied to the frequency dimension.

**Comment by plaplant** [comment]
@jsdillon ping

**Comment by jsdillon** [comment]
This is done.
