### ISSUE TITLE
Confusing vis_clean doc string... or maybe an error in functionality?

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_cal#425]
An issue came up during @adampbeardsley update of delay_xrfi. Adam was trying to build a VisClean subclass (DelayFilter) using a HERAData object, on which he had already performed a read(), so self.hd.data_array was not None. VisClean's init will attach a HERACal object with input_cal to the object, but in this case it won't actually apply the calibration because it fails this if statement:

https://github.com/HERA-Team/hera_cal/blob/8e3d07dc8592d02d43c2f0a0116b9b391e9080e3/hera_cal/vis_clean.py#L81

So, either this docstring is wrong in the case where VisClean is inited with a UVData/HERAData object which already has data in it, or we need to change the logic of the init:

https://github.com/HERA-Team/hera_cal/blob/8e3d07dc8592d02d43c2f0a0116b9b391e9080e3/hera_cal/vis_clean.py#L37-L39

**Comment by nkern** [comment]
how did it fail at `self.hd.data_array is not None` if he *already* did a read, and thus `hd.data_array` is not None?

**Comment by adampbeardsley** [comment]
For the record, I haven't actually tried this out yet. Josh just noticed the inconsistency in the doc string as we were sorting out what _should_ be done.
