### ISSUE TITLE
Reference Antennas and Phase Noise with New Abscal

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_cal#434]
I've been looking at some of the results out of Abscal with the new abscal model for IDR2.2 / IDR3.1. The good news is that the absolute values look very similar (though maybe slightly noisier than in IDR2.1:

![screen shot 2019-01-28 at 2 44 42 pm](https://user-images.githubusercontent.com/5281139/51871484-4d4cc500-230b-11e9-9ee2-889a1dcdf7f8.png)

However, our new abscal implements automatic phase reference selection. Currently, this picks the lowest number antenna among those with the fewest flags:

https://github.com/HERA-Team/hera_cal/blob/5968168f88f4b8ef92f48aaea59462069f9d6624/hera_cal/smooth_cal.py#L194

Looking at 2458098.45361, the code picked (1, 'Jyy'). I think we want to pick a single antenna-pol phase reference for all gains, both Jxx and Jyy, since we only really have one degree of freedom, the overall phase. In theory, giving both polarizations an overall phase degree of freedom independently will screw up the calibration for xy and yx visibilities.

At any rate, this seems to produce pretty noisy phase solutions, compared to IDR2.1:
![screen shot 2019-01-28 at 2 51 08 pm](https://user-images.githubusercontent.com/5281139/51871775-2c38a400-230c-11e9-8ce9-21d17dca4f1c.png)

It seems like most of the problem is just due to picking a bad reference antenna--if it's phase solution is noisy, that noise gets spread out over the whole array. This doesn't matter for calibrating visibilities, but it does matter for identifying RFI using gain solutions (if we use complex values, at least) and it does matter for smoothing gain solutions.

If we just use (53, 'Jxx'), the manually selected reference antenna for IDR2.1, things generally look better:

![screen shot 2019-01-28 at 2 57 16 pm](https://user-images.githubusercontent.com/5281139/51872068-11b2fa80-230d-11e9-864a-2959377872f5.png)

So the issue is mostly one of selecting a good antenna automatically.

Here's my proposed algorithm:
- Identify all antenna-polarizations with the minimum number of flags. These are refant candidates.
- For each refant candidate
	- Take out an constant and freq-independent delay and phase from each antenna's gain
	- Compute the noise in that antenna's angle(gain) when rephased to the candidate refant, using interleaved differencing.
	- Take a median over that noise waterfall (this should take care of phase wraps).
	- Take a median of those medians over all unflagged antennas. This is the "phase noise metric"
- Find the antenna with the lowest phase noise metric.

When I do this, I find that (86, 'Jyy') rises to the top with a phase noise metric of 0.00195. By contrast. And for reference, (53, 'Jyy') which was used for yy-polarization in IDR2.1, is 0.00245. (1, 'Jyy') is the worst antenna, as it turns out with 0.00419, which is interesting to see. The metric also has some interesting position structure:

![screen shot 2019-01-28 at 3 08 38 pm](https://user-images.githubusercontent.com/5281139/51872618-052fa180-230f-11e9-9a47-08c8a61ce8d7.png)

and using (86, 'Jyy') produces decent-looking results:

![screen shot 2019-01-28 at 3 12 18 pm](https://user-images.githubusercontent.com/5281139/51872670-25f7f700-230f-11e9-9f9c-74a57b9f2e37.png)

So this seems like a reasonable solution. Thoughts @adampbeardsley or @nkern?

**Comment by jsdillon** [comment]
Hmmm... I think you're right about that... at least as long as we don't include xy and yx visibilities in the abscal model. I'll play around with a fix that produce a single reference antenna or one per polarization.

**Comment by nkern** [comment]
I think its better to have a single reference antenna for the entire night. I assume this metric operates on a per file basis, which means there is the possibility of it changing file by file. I'm fine w/ a hardcoded antenna 53 refant for IDR2.2

**Comment by jsdillon** [comment]
The plan is for abscal to pick a reference antenna per-file, but then to have smooth_cal pick one for the whole night based on the same procedure but with more data. Smooth_cal is the first step that has visibility into the whole night, so it makes sense to do it there.
