### ISSUE TITLE
Update README and documentation to reflect hera_cal / hera_qm split

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_cal#45]

**Comment by SaulAryehKohn** [comment]
README is changed but ReadTheDocs is not.

**Comment by bhazelton** [comment]
In pyuvdata, we actually create the RTD index file dynamically from the readme. If you'd like to implement something similar in for hera_cal, you'd need something similar to pyuvdata/docs/make_index.py and you'd also need to add a few lines of code to your docs/conf.py along the lines of what we have in pyuvdata from lines 306 onward.

**Comment by jsdillon** [comment]
I'm closing this in favor of #507, which is a more general issue.
