### ISSUE TITLE
[H3C RTP]: systematics before or after LST binning?

### ISSUE THREAD

**Issue by nkern** [HERA-Team/hera_cal#488]
We should briefly consider whether we want to perform xtalk and reflection calibration before on-the-fly binning. My opinion is that we don't need to do this on a nightly basis (aka before binning), because the systematics generally seem to be stable night-to-night.

**Comment by jsdillon** [comment]
Along with #486, we need to figure this out with IDR2.2 so we can make a decision about the architecture of the RTP. @nkern do you still want to take this on?

**Comment by jsdillon** [comment]
Discussed 9/4. We think we can close this issue. @nkern will write up why shortly.

**Comment by nkern** [comment]
We don't yet have evidence that we _need_ to perform systematic removal on a nightly basis, so we will defer to doing it on LST binned products. The concern is that if the systematics are changing night-to-night then this will make it harder to remove them after binning.
For xtalk removal this should be fine, as it is essentially just a filter, so it doesn't matter if it is changing night to night that much.
For cable reflections this is more of a concern b/c it is modeled as a multiplicative effect, but we don't yet have evidence that cable reflection terms are changing significantly night to night, although if I had to guess this would be the first thing we see as a limitation to post-binned systematic removal.
