### ISSUE TITLE
Compute noise on LST-binned data from autocorrelations and sqrt(Bt) and Nsamples

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_cal#490]
We're not sure if this can be done with LST-binned autocorrelations or not.

**Comment by jsdillon** [comment]
I worked out the math on this. If the autocorrelations don't vary from day to day substantially, then the noise shouldn't either and this calculation is trivial. 

[Noise.Variance.Comparison.Diff.vs.Autos.pdf](https://github.com/HERA-Team/hera_cal/files/3283660/Noise.Variance.Comparison.Diff.vs.Autos.pdf)

So the real question is, do the calibrated autocorrelations change substantially from day to day?

**Comment by jsdillon** [comment]
I have checked the variance in autocorrelations between days compared to the autocorrelations themselves in IDR 2.2. It looks like the variation in autocorrelations from day to day is at the ~1% level across most of the band, consistent with our uncertainty in the calibration solutions.

![Screen Shot 2019-07-24 at 6 19 43 PM](https://user-images.githubusercontent.com/5281139/61838756-aff8c680-ae3f-11e9-8894-fbedb18dac87.png)

This means that the approximation in equation 5 of the above PDF is quite good. I believe we can close this issue. @acliu thoughts? Does this need to be written up somewhere (like a memo) or is this good enough?

**Comment by acliu** [comment]
I think this is reasonable, and at this level I don't think a memo is needed. There are just two points that might be worth considering:
- I see you've averaged over all antennas. I'd be curious to know what the worst-case scenario. How deviant is your worst antenna?
- Have you seen any systematic trends? You say that the variation is at the ~1% level, but if these variations are random it's qualitatively different than if it's, say, an oscillation with a 1% amplitude.

**Comment by jsdillon** [comment]
This is kind of interesting. 

![image](https://user-images.githubusercontent.com/5281139/61899943-6953ac80-aed1-11e9-8b2f-5d511b9746e4.png)

There's definitely a few antennas that show higher variance. Likely something weird happened where their calibration varies more from day to day than other antennas...

The maximum is dominated by a single antenna, 70x. The next highest is < .05 over most of the band.

**Comment by acliu** [comment]
Very interesting. So the coherent ripple you see in the orange max curve is dominated by 70x? Do the other ones also show the same ripple with frequency (albeit at a much lower amplitude) or do the more well-behaved antennas generally show flatter trends?

It seems like the easiest thing to do might be to:

1. Exclude 70x from our pspec measurements and see what happens.

2. Include it, but to perturb the input covariance for just the baselines that involve that antenna by -20% and +20%, and to see how much it affects our final error bars on the pspec.

Does that seem reasonable to you?

**Comment by jsdillon** [comment]
They all show some spectral structure, but not a ton. Here the worst antennas (median ratio > 2%) are bolded and included in the legend.

![image](https://user-images.githubusercontent.com/5281139/61976408-928f3e00-afa0-11e9-9235-10e043fa6c2f.png)

I'm not sure if excluding 70x is the right answer... it might be an LST-dependent effect. It also might only affect the even or odd days. There's a lot to look into. @nkern curious if you have any thoughts?

**Comment by acliu** [comment]
Ok, that’s fine. But from the pspec perspective we will just bracket the range of possibilities for now and you can let us know when you’ve dug into this more.

**Comment by jsdillon** [comment]
Ok. I think the short answer is that we can use the autocorrelations as a good proxy for the noise. Even in the worst case scenario (20% variability from day to day), equation 5 is probably a pretty good approximation and usually it's very good.

I'm closing this issue in favor of #513
