### ISSUE TITLE
io.to_HERACal returns empty object when input is non-existant file

### ISSUE THREAD

**Issue by nkern** [HERA-Team/hera_cal#525]
`io.to_HERACal('not_a_file')` returns a valid but empty `HERACal` object. this should instead raise an IO error

**Comment by jsdillon** [comment]
So this behavior is "expected" in the sense that if you initialize a `HERACal`object with a file that doesn't exist, it doesn't complain until you try to do `.read()`.

This is also true if you initialize a `HERAData` object with any filetype other than `.uvh5`.

We could stick in assertions that the files exist in the constructors. Is that useful or important?

**Comment by nkern** [comment]
I had an issue trying to use this on many files, some of which seemed to not actually exist.

It seems a little misleading when feeding`not_a_file` to have it return an empty object, which reasonably should be the case if you did `io.to_HERACal(None)` or `io.to_HERACal()`. Probably we should put an `assert os.exists(fname)` or something
