### ISSUE TITLE
Time to dump python 2?

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_cal#547]
The recent troubles with the IERS table and astropy have made it pretty clear that it's getting to be more trouble supporting python 2 than it's worth. IDR2.2 was run entirely with python 3, as will all future IDRs. Are we ready to dump support for python 2 and remove it from travis?

Any objections from @AaronParsons, @nkern, @plaplant, @adampbeardsley, or @bhazelton?

Also, we should handle this simultaneously with #507 and #511.

**Comment by adampbeardsley** [comment]
I'm down.

**Comment by bhazelton** [comment]
It's fine with me, pyuvdata will be dropping it by the end of the year anyway.
