### ISSUE TITLE
antenna names from data files are not preserved on related calibration files.

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/hera_cal#586]
Caused by (currently) line 1429 in io.py in the `write_cal` method, which just prepends "ant" to the antenna number. Generically antenna numbers do not need to match their names. This may cause issues in pyuvdata's uvcalibrate method in the future, we are adding consistency checks between the UVCal and UVData objects, including one on antenna names.

https://github.com/HERA-Team/hera_cal/blob/be193e97fcde36e0e0e964405fccc91015111f2d/hera_cal/io.py#L1429

**Comment by nkern** [comment]
Thanks @bryna ,I think the way to address this is to provide an optional antenna_names list. otherwise default to what is currently here.

**Comment by jsdillon** [comment]
Alternatively, we could have write_cal take in a HERAData/UVData object and use it to write out all the relevant properties. I could see requiring a HERAData/UVData object and then using kwargs to overwrite any properties that you don't want to copy from that object. 

This wouldn't be too onerous of a change, I think... and also a good way to bring over histories.

**Comment by nkern** [comment]
I'm making a PR for this btw @jsdillon

**Comment by jsdillon** [comment]
This is closed by #588
