### ISSUE TITLE
Enabling filtering of antennas to only calibrated "redundantly calibratable" antennas.

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_cal#590]
Some antenna configurations are not classically "redundantly calibratatable" in the sense that they introduce more than 2 tip/tilt degeneracies. Right now abscal can only solve for a single EW tilp/tilt and a single NS tip/tilt per polarization. The simplest solution is to have redcal flag the smallest number of antennas possible to reduce the dimensionality of the problem. A better solution would be give more tip/tilt DoF to abscal. I'll make that a separate issue...

EDIT: see #592 

This turns out to have been an issue for H3C in a way that depends sensitively on antenna flagging. For example, if we flag only the black antennas, the array is redcalable but if we also flag the red ones, it is no longer.

![image](https://user-images.githubusercontent.com/5281139/79412770-2653d080-7f5b-11ea-9fe6-c1cf303865d2.png)

This turns out to have been the source of the phase discontinuities in abscal that I've been chasing down for a month or so.

Here's a phase after redcal and  abscal using RIMEz on 2458792 when we only flag the black antennas:

![image](https://user-images.githubusercontent.com/5281139/79412882-59965f80-7f5b-11ea-9dab-a7c4f7c5ee99.png)

And here's what it looks like when we flag to the red ones too:

![image](https://user-images.githubusercontent.com/5281139/79412905-6adf6c00-7f5b-11ea-9b91-8b861257be9f.png)

**Comment by nkern** [comment]
@jsdillon nice!

**Comment by jsdillon** [comment]
Thanks @nkern. Curious about your opinion of #592
