### ISSUE TITLE
DPSS interpolation causes popups in flagged band edges

### ISSUE THREAD

**Issue by aewallwi** [HERA-Team/hera_cal#605]
Also see https://github.com/HERA-Team/uvtools/issues/74

DPSS interpolants can be wildly off in channels that are flagged at the band edges. Right now, there is a `maximum_continguous_edge_flags` argument that skips time/freq integrations with to many edge flags. However, the interpolants are fine off the band edge so I think the right solution is to just keep any edge flags that exist in the original data (where we know the interpolants are going to be way off). 

I'm not sure if we should cover this here are in `uvtools`. `uvtools` is probably a better place but I thought I'd also raise this here for people to be aware of. 

![image](https://user-images.githubusercontent.com/6164284/83200152-8bbce480-a0f7-11ea-82a4-f9467dc31bb2.png)

**Comment by jsdillon** [comment]
This definitely seems like a uvtools issue, so as long as whatever you come up with doesn't break hera_cal, I'm cool with it.

**Comment by aewallwi** [comment]
The features in #674 now address this.
