### ISSUE TITLE
Reading multiple data files scales quadratically with the number of files. Can it be made linear?

### ISSUE THREAD

**Issue by zacharymartinot** [HERA-Team/hera_cal#648]
@AaronParsons mentioned on the main telecon that reading in data for a day seems to take way longer than it should, I've had the same thought. I briefly took a look under the hood (while i was waiting...) so here's what I think is going on.

It looks to me like the problem is the way UVData handles multiple files. When reading, the n'th file in the list is compared to the concatenation of the previous (n-1) files. This effectively ends up comparing every file in the list to every other file, so the scaling is quadratic in the number of files. The `fast_concat` method improves the runtime by doing fewer checks, but it is still comparing all-to-all so the scaling is still quadratic, just with a reduced prefactor. However, our actual use-case with HERA data is that we have a large number of data files that we already know are homogeneous and compatible. So it seems like we should be able to make it linear by only checking that every file matches the first, defining appropriately sized arrays for the in-memory object, then loading each file's data into its proper place.

I haven't gone any further than a brief browse of the code so (assuming the above assessment is correct) I'm not really sure how hard this is or whether this can be HERAData thing, or if it would have to be a modification to UVData. @plaplant @jsdillon ?

**Comment by jsdillon** [comment]
I think the short answer is that it's definitely possible, but it would be a bunch of work (if you're interested, I'm all for it). My experience is that the fast_concat makes things fast enough, though it does involve a lot of steps that reallocate memory.

I do think we'd be better off if pyuvdata did this than if we did, since if HERAData needs to do a lot of manipulation of UVData attributes like `data_array`, we run much more risk of the subclass becoming incompatible with updates to the main class.

**Comment by nkern** [comment]
@zacharymartinot I have an _OLD_ PR in pyuvdata which attempted to solve this problem by utilizing the homogeneity of the input files, generating a single large `data_array` and then populating it with the individual files, which saw a fairly large speed-up in data concatenation. I mentioned it here (https://github.com/RadioAstronomySoftwareGroup/pyuvdata/issues/383) and the branch is still open `uvdata_combine_func`). If someone wants to pick this up please feel free to use this if it helps.

**Comment by zacharymartinot** [comment]
Addressed in https://github.com/RadioAstronomySoftwareGroup/pyuvdata/pull/937
