### ISSUE TITLE
Faulty standard deviation calculation in LST-binning

### ISSUE THREAD

**Issue by matyasmolnar** [HERA-Team/hera_cal#744]
I think I have found an issue when the standard deviations are calculated in `lst_bin`, see [here](https://github.com/HERA-Team/hera_cal/blob/7829a309519cef386d0053c33673b78e80901dde/hera_cal/lstbin.py#L380).

The `real_std` and `imag_std` are calculated from the `d` variable, which has been zero-padded for nans (all flagged indices have been nan'd at this stage) just above `here` with `d[~isfinite] = 0.0` (that is if `median = False` as the `if median:` branch above does not affect `d`).

The nan indices are therefore not discarded in `np.nanstd` and the zeros are contributing to the resulting standard deviation.

A quick fix would be to have, e.g.:
```
d_w = d.copy()
isfinite = np.isfinite(d_w)
d_w[~isfinite] = 0.0
n[~isfinite] = 0.0

norm = np.sum(n, axis=0).clip(1e-99, np.inf)
real_avg.append(np.sum(d_w.real * n, axis=0) / norm)
imag_avg.append(np.sum(d_w.imag * n, axis=0) / norm)
```
which then does not modify d
alternatively, the weighted average could be done with `np.ma.average` with `weights=n` and `mask=np.isnan(d)` .

**Comment by jsdillon** [comment]
Fixed via #745
