### ISSUE TITLE
Get lsts in read_hera_hdf5

### ISSUE THREAD

**Issue by aewallwi** [HERA-Team/hera_cal#809]
`io.read_hera_hdf5` does not currently appear to return an array of lsts as part of the `info` dict (only returns JD times).

**Comment by jsdillon** [comment]
`io.read_hera_hdf5`, as @AaronParsons wrote it, only gets metadata directly from the file with no manipulation. LSTs are an example of metadata not actually in the file but inferable from the JDs and the telescope location. 

You want `io.HERADataFastReader` which is meant to be a drop-in replacement for `io.HERAData` in many places. For example, the `DataContainer`s it produces should have the same structure and metadata.
