### ISSUE TITLE
Make master protected branch?

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_cal#90]
In reviewing a PR, I just noticed that master is not actually protected, and reviews are not required. I strongly recommend doing this to help prevent spurious commits to production code.

**Comment by plaplant** [comment]
For my $0.02, I whole-heartedly agree with making master protected and requiring reviews. I talked with @jsdillon about this some time ago, and I think the concern was that it might slow down development. I don't think that's actually been a concern in practice, and we almost always end up having someone review the code before merging anyway. We might as well make it official.

**Comment by jsdillon** [comment]
I tried to do this and I think I screwed up. I added specific people who could push to master but it said that all administrators were able to push to master by default. So I downgraded hera_dev from admin to writer, but apparently downgraded myself too! Now I'm not sure who owns the repo...

@plaplant @adampbeardsley help?

**Comment by jsdillon** [comment]
I'll meet you guys halfway. I've restricted who can push to the master branch, but I don't want to force reviews and branching for truly minor changes or force re-reviews after a small change is requested on a PR. I trust the group (you two, me, zaki, saul, paul, aaron, and danny) to not do anything too stupid.
