### ISSUE TITLE
Firstcal functionality need to be internal to Firstcal Object, not in firstcal_run()

### ISSUE THREAD

**Issue by AaronParsons** [HERA-Team/hera_cal#96]
We need a single functional interface to running firstcal.  firstcal_run() has too much smarts inside of it (particularly in _search_and_iterate_firstcal() ), and its functionality is tied up with option parsing and output json file formats.  This does not provide a single-stop interface for doing just firstcal (without file formats or option parsing) in custom scripts.  

Generally, we need a sharper division between the core functionality of the code and the interfaces to the code, and as a rule, we should *never* require option_parsers or files on disk to run a piece of code.

**Comment by jsdillon** [comment]
Made irrelevant by #384.
